version: '3.9'

services:
  api:
    container_name: warhoop-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - CI_COMMIT_REF_NAME=master
    ports:
      - "3011:3011"
    restart: unless-stopped
    depends_on:
      - warhoopdb
    networks:
      - warhoop-network

  warhoopdb:
    container_name: warhoop-db
    image: 'jc21/mariadb-aria:latest-innodb'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'warhoop'
      MYSQL_DATABASE: 'sait'
      MYSQL_USER: 'warhoop'
      MYSQL_PASSWORD: 'warhoop'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - warhoop_db:/var/lib/mysql
      - ../sql/init/sait.sql:/docker-entrypoint-initdb.d/sait.sql:ro
    networks:
      - warhoop-network

networks:
  warhoop-network:
    name: warhoop-network
    driver: bridge

volumes:
  warhoop_db:
    name: warhoop_db