service:
  log_level: "info"
  log_folder: "log"
  log_prefix: "auth"
  api_addr_port: "0.0.0.0:3011"
  app_url: "https://warhoop.su"
  git_info: "static/gitinfo.json"
  template_welcome: "templates/welcome.html"
  template_static: "static/welcome.html"
  default_locale: "ru"

db:
  auth: "123:123@tcp(192.168.1.33:3306)/auth?parseTime=true"
  characters: "123:123@tcp(192.168.1.33:3306)/characters?parseTime=true"
  world: "123:123@tcp(192.168.1.33:3306)/world?parseTime=true"
  sait: "warhoop:warhoop@tcp(warhoop-db:3306)/sait?parseTime=true"
  verbose: false

cors:
  allow_origins: "http://localhost:5173,http://192.168.1.33:5173"
  allow_methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  allow_headers: "Content-Type,Authorization"
  allow_credentials: true

mail:
  server: ""
  port: ""
  user: ""
  password: ""
  sander_name: ""
  folder_templates: "templates"
  template_verify: "verify.html"
  template_password: "password.html"
  template_login: "login.html"
  template_password_complete: "change_password_complete.html"
  template_change_email: "change_email.html"

cookie:
  name: "warhoop"
  domain: ""
  httpOnly: true
  secure: false
  sameSite: "None"
  access_duration: "12h"
  jwt_key: "secret_key"